Rollback GitLab CI - wrong app

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,71 +1,81 @@
-# Add Code Quality reporting automatically (built into Gitlab)
-#include:
-#  - template: Code-Quality.gitlab-ci.yml
-#  - template: Dependency-Scanning.gitlab-ci.yml
-#  - template: SAST.gitlab-ci.yml
+# Tests (dependency scanning, licenses, scope, etc) happen for all branches and merges. 
+# Actual package publishing only happens once the project has been tagged. 
 
-# Local paths that are cached between jobs. Each job runs in
-# a separate EC2 instance, these cached files are stored in
-# an S3 bucket and copied to each job instance.
-cache:
-  key: "$CI_COMMIT_REF_SLUG" # Each branch has a separate cache
-  paths:
-    # Paths added as part of the install stage
-    - vendor
-    - node_modules
+# Nice to have TODOs:
+# - Automatically do an `npm install && npm build`
+# - Automatically determine the build number from the branch and update package.json on master accordingly
+#   (e.g. your typical "chore: update package version [skip ci]" type of bot commit)
 
-stages:
-  - install
-  - build
-  - deploy
+# Include some template jobs that integrate with GitLab's Security & Compliance
+include:
+  - template: Dependency-Scanning.gitlab-ci.yml
+  - template: Security/License-Scanning.gitlab-ci.yml
 
-# Hidden base job for PHP work
-.php_job:
-  # Build that our servers use
-  image: php:7.2-alpine
-
-# Hidden base job for Node work
+# Hidden job - used as a base for common settings in other jobs
 .node_job:
+  # Image locked to node:15.4 due to a bug with npm publish ignoring custom registries in node:latest (as of 12/29/2020)
   image: node:15.4
 
-Run Composer Install:
-  extends: .php_job
-  stage: install
-  script:
-    - apk update
-    - apk add --no-cache git curl
-    # Download and run composer
-    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
-    - composer install --no-interaction --no-scripts --no-suggest --no-plugins --optimize-autoloader
-    # For production, we'd add: --no-dev, but we need it for now to run phpunit and friends.
+  # Validate that the repository contains a package.json and extract a few values from it.
+  before_script:
+    - |
+      if [[ ! -f package.json ]]; then
+        echo "No package.json found! A package.json file is required to publish a package to GitLab's NPM registry."
+        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#creating-a-project'
+        exit 1
+      fi
+    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
+    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
 
-Run NPM Install:
-  extends: .node_job
-  stage: install
-  script:
-    - npm install
-
-Build React App:
+# Validate that the package name is properly scoped to the project's root namespace.
+# For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention
+validate_package_scope:
   extends: .node_job
   stage: build
-  dependencies:
-    - install
-  script:
-    - npm run build
-    
-Deploy App:
-  extends: .php_job
-  dependencies:
-    - build
-  only:
-    - master
   script:
     - |
-      curl
-        --data "JOB_ID=$CI_JOB_ID" \
-        --data "PROJECT_ID=$CI_PROJECT_ID" \
-        --data "PROJECT_NAME=$CI_PROJECT_NAME" \
-        --data "COMMIT_REF=$CI_COMMIT_REF_NAME" \
-        --data "COMMIT_BRANCH=$CI_COMMIT_BRANCH" \
-        "https://orapps.osu.edu/orchestrator/artifact"
-        
+      if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
+        echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
+        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
+        exit 1
+      fi
+
+# If no .npmrc if included in the repo, generate a temporary one to use during the publish step
+# that is configured to publish to GitLab's NPM registry
+create_npmrc:
+  extends: .node_job
+  stage: build
+  only:
+    - tags
+  script:
+    - |
+      if [[ ! -f .npmrc ]]; then
+        echo 'No .npmrc found! Creating one now. Please review the following link for more information: https://docs.gitlab.com/ee/user/packages/npm_registry/index.html#authenticating-with-a-ci-job-token'
+
+        {
+          echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
+          echo '//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
+          echo '//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
+        } >> .npmrc
+
+      fi
+  artifacts:
+    paths:
+      - .npmrc
+
+# Publish the package. If the version in package.json has not yet been published, it will be
+# published to GitLab's NPM registry. If the version already exists, the publish command
+# will fail and the existing package will not be updated.
+publish_package:
+  extends: .node_job
+  stage: deploy
+  only:
+    - tags
+  script:
+    - |
+      {
+        npm publish &&
+        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
+      } || {
+        echo "No new version of ${NPM_PACKAGE_NAME} published. This is most likely because version ${NPM_PACKAGE_VERSION} already exists in GitLab's NPM registry or another error has occurred in npm publish." && exit 1
+      }
